[package]
name = "rango"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.1.3", features = ["sqlite"] }
serde = { version = "1.0.190", features = ["derive"] }
rocket = { version = "0.5.0", features = ["json"] }
rocket_cors = { version = "0.6.0" }
dotenv = "0.15.0"
rust-crypto = "0.2.36"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.8"
