[package]
name = "controllers"
version = "0.1.0"
edition = "2021"

[dependencies.rusql-alchemy]
version = "0.1.0"
git = "https://github.com/j03-dev/rusql-alchemy"
branch = "main"

[dependencies.models]
path = "../models"

[dependencies]
rocket = { version = "^0.5.0", features = ["json"] }
serde = { version = "^1.0.203", features = ["derive"] }
