[package]
name = "app"
version = "0.1.0"
edition = "2021"


[dependencies.controllers]
path = "../controllers"

[dependencies]
rocket = { workspace = true }
rocket_dyn_templates = { workspace = true }
