[package]
name = "migrate"
version = "0.1.0"
edition = "2021"


[dependencies.models]
path = "../models"

[dependencies]
rusql-alchemy.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
