[package]
name = "migrate"
version = "0.1.0"
edition = "2021"


[dependencies.models]
path = "../models"

[dependencies]
rusql-alchemy = { workspace = true }
tokio = { version = "^1.38.0", features = ["macros", "rt-multi-thread"] }
