[package]
name = "models"
version = "0.1.0"
edition = "2021"

[dependencies.rusql-alchemy]
version = "0.1.2"
default-features = false
features = ["postgres"]

[dependencies]
sqlx = "^0.7.0"
serde = { version = "^1.0.203", features = ["derive"] }